spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: 3.0

cards:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (111) 555-1234
    - (111) 523-1345
